# -*- code utf-8 -*-
from flask import Flask

from app.services import ServicesLoader
from app.config import config

from app.www.mobile.module import MobileMod
from app.models import database

app = Flask(__name__)
app.config.from_object(config)

services_loader = ServicesLoader(app)
mobile_mod = MobileMod(app)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    database.connect()


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not database.is_closed():
        database.close()

